### ISSUE TITLE
panic in --release build

### ISSUE THREAD

**Issue by mjanda** [kubo/rust-oracle#1]
Hello,
I've tried to use this library and it works in debug builds. But when I compile them with `cargo build --release`, I'll get following panic.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OCI Error: (code: 0, offset: 0, message:, fn_name: dpiConn_create, action: start)', /checkout/src/libcore/result.rs:906:4
```

It happens when calling `oracle::Connection::new` - I've reduced my code to basically creating connection in `main`.

rustc 1.23.0-beta.2 (c9107ee93 2017-12-08)
on ubuntu

I'm just learning rust, so I'm not sure if I can be more helpful with debugging, but I'll try if needed.

**Comment by kubo** [comment]
Thank you for the report.
I reproduced it in release builds with rust 1.20, 1.21 and 1.22.1.
However there are no problem with rust 1.18 and 1.19.

I checked the generated machine code and found that the `chkerr` macro
was expanded incorrectly.
It returns an error without checking the result of `dpiConn_create()`.
https://github.com/kubo/rust-oracle/blob/62a7fafe0028ad3d31b5640db8ec35a55570f7bb/src/connection.rs#L893-L897
https://github.com/kubo/rust-oracle/blob/62a7fafe0028ad3d31b5640db8ec35a55570f7bb/src/error.rs#L340-L344

I'll dig deep into it.

**Comment by kubo** [comment]
@mjanda Could you change two `conn_param` variables in [this line](https://github.com/kubo/rust-oracle/blob/62a7fafe0028ad3d31b5640db8ec35a55570f7bb/src/connection.rs#L901) to `param`?
Thought I don't know the reason, it fixed the issue as far as I checked.
I'll commit it later because I'm out now.

**Comment by mjanda** [comment]
Thank you, this change seems to work fine.

**Comment by kubo** [comment]
I opened a rust issue. I think that it is a bug in optimization in rust.
https://github.com/rust-lang/rust/issues/47123
