### ISSUE TITLE
Memory is not released on multithreading.

### ISSUE THREAD

**Issue by nao-kobayashi** [kubo/rust-oracle#13]
My environment is windows10.
rust's version is 1.35.0(stable-msvc).
crate oracle 0.2.1

My application hangs up due to out of memory.
I watched details of memory usage when my application hangs up.
It seems memory and handles are not release.

The following is a simplification of my code.
To create threads, then individual thread connects oracle and executes query.
After long time running, out of memory is going to happen.
Allocated memory never release and reuse.

Is my code somthing wrong?
(I modified previous post.)

```
extern crate oracle;
use oracle::Connection;
use std::thread;

fn main() {
    let limit = 1000;
    thread::spawn(move || {
        for _ in 0..limit {
            let h = thread::spawn(move || {
                let conn = Connection::connect(
                	"user", 
                	"pass", 
                	"192.168.1.1:1521/orcl", 
                	&[]).unwrap();
                conn.close().unwrap();
            });
            h.join().unwrap();
        }
    }).join().unwrap();

    println!("finished");
    let mut word = String::new();
    std::io::stdin().read_line(&mut word).ok();
}
```

**Comment by kubo** [comment]
@nao-kobayashi 
Could you try https://github.com/kubo/issue13?
```shell
$ git clone https://github.com/kubo/issue13.git
$ cd issue13
# change username, password and database in src/main.rs
$ cargo run -- -t
```
When the program runs with the `-t` option, it establishes connections in threads as your program does.  
It works well on linux with and without the `-t` option.
It works well on Windows without the `-t` option.  
However it stops with `STATUS_STACK_BUFFER_OVERRUN` error on Windows with the `-t` option.
I guess that some defects are in rust-oracle, in [ODPI-C][] or especially in Oracle client library.

[ODPI-C]: https://oracle.github.io/odpi/

**Comment by nao-kobayashi** [comment]
Having some defects in Oracle Client library might be true. 
I updated instant client 12.1 to latest version. 
Then it seems to solve this problem.
(My program does't stop STATUS_STACK_BUFFER_OVERRUN error.)
I'm sorry, I didn't try InstantClient's latest version until now.

Thank you so much for your kindness.
