### ISSUE TITLE
Return type expects lifetime Parameter

### ISSUE THREAD

**Issue by lantonides** [kubo/rust-oracle#17]
The following code gives the error[E0106]: missing lifetime specifier at <ResultSet<Row>>.

'''use oracle::{Connection, ResultSet, Row};

fn oracle_connect(uid: &str, pass: &str, server: &str, sql: &str) -> oracle::Result<ResultSet<Row>> {
    let conn = Connection::connect(uid, pass, server)?;
    let mut stmt = conn.prepare(sql, &[])?;

    stmt.query(&[])
}
'''
According to the manual this is how the return type is written but it doesn't work.

**Comment by kubo** [comment]
What manual do you see? You need to learn [lifetime](https://doc.rust-lang.org/book/ch10-03-lifetime-syntax.html).

ResultSet is defined as
```rust
pub struct ResultSet<'a, T> where T: RowValue
```
It requires lifetime.

Your `oracle_connect` function doesn't have lifetime annotations. So the rust compiler try to apply the lifetime elision rules. However the signature doesn't match any of the three rules. Therefore the compiler complains that missing lifetime specifier.

However you cannot use the function even though you add lifetime annotations. You need to change the function signature.

The method signature of `Statement.query` is:
```rust
    pub fn query(&mut self, params: &[&dyn ToSql]) -> Result<ResultSet<Row>>
```
It is simplified by lifetime elision. It is same with the next.
```rust
    pub fn query<'a>(&'a mut self, params: &[&dyn ToSql]) -> Result<ResultSet<'a, Row>>
```
This means that `self`(`Statement`) must live longer than the return value(`ResultSet`).
However `Statement` is dropped at the end of `oracle_connect` but the function try to return `ResultSet`. The borrow checker doesn't allow it.
```rust
use oracle::{Connection, ResultSet, Row};

fn oracle_connect(uid: &str, pass: &str, server: &str, sql: &str) -> oracle::Result<ResultSet> {
    let conn = Connection::connect(uid, pass, server)?; // ^ lifetime of conn
    let mut stmt = conn.prepare(sql, &[])?;             // |  ^ lifetime of stmt
    stmt.query(&[])                                     // |  |
                                                        // |  v
                                                        // v
}
```

**Comment by kubo** [comment]
I changed your code to pass compilation. Note that I won't use it in my applications because it isn't efficient.

```rust
use oracle::{Connection, Row};

fn oracle_connect(uid: &str, pass: &str, server: &str, sql: &str) -> oracle::Result<Vec<Row>> {
    let conn = Connection::connect(uid, pass, server)?;
    let mut rows = Vec::new();
    for row_result in conn.query(sql, &[])? {
        rows.push(row_result?);
    }
    Ok(rows)
}
```
