### ISSUE TITLE
cargo:warning=cl : Command line error D8021 : invalid numeric argument '/Wno-unused-parameter'

### ISSUE THREAD

**Issue by vlad-korotych** [kubo/rust-oracle#2]
I have an error on win10:
running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "odpi/include" "/I
" "odpi/src" "/W4" "-Wno-unused-parameter" "/FoC:\\Rust\\rms\\target\\debug\\build\\oracle-a41627ac717eac75\\out\\odpi/src\\dpiConn.o"
"/c" "odpi/src/dpiConn.c"
cargo:warning=cl : Command line error D8021 : invalid numeric argument '/Wno-unused-parameter'
exit code: 2

To fix this error I removed line .flag("-Wno-unused-parameter") from build.rs. And now it works for me.

**Comment by kubo** [comment]
Thank you!
The `-Wno-unused-parameter` is an option for gcc compiler. It should be set only for gcc.

**Comment by kubo** [comment]
@vlad-korotych Thaks. I apply `-Wno-unused-parameter` only when it is supported by using [flag_if_supported](https://docs.rs/cc/1.0.4/cc/struct.Build.html#method.flag_if_supported).

**Comment by vlad-korotych** [comment]
Thanks!
