### ISSUE TITLE
How do I set socket_timeout? I didn't find related examples or instructions in the project

### ISSUE THREAD

**Issue by sMitea** [kubo/rust-oracle#24]

**Comment by kubo** [comment]
Use sqlnet.ora for now. I'll add a method using [dpiConn_setCallTimeout](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_setCallTimeout) later.

Create a file containing the following and save it as `sqlnet.ora`.
```
SQLNET.RECV_TIMEOUT=30
SQLNET.SEND_TIMEOUT=10
TCP.CONNECT_TIMEOUT=10
```
Set the environment variable `TNS_ADMIN` pointing to the directory containing the `sqlnet.ora` file.
See [this document](https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-19423B71-3F6C-430F-84CC-18145CC2A818) for more details.

**Comment by sMitea** [comment]
@
