### ISSUE TITLE
connection pooling

### ISSUE THREAD

**Issue by rursprung** [kubo/rust-oracle#33]
in the TODO list of your README you mention connection pooling. what are your plans there? i provide [`r2d2-oracle`](https://crates.io/crates/r2d2-oracle) which wires up your `oracle` with the [`r2d2`](https://crates.io/crates/r2d2) connection manager.
is this enough? maybe it'd make sense to strike this list from your TODO and instead point to `r2d2-oracle` in your README?

**Comment by kubo** [comment]
The connection pooling in README means session pools supported by [ODPI](https://oracle.github.io/odpi/doc/functions/dpiPool.html).

It is worth to point to `r2d2-oracle`. Thanks.
