### ISSUE TITLE
Oracle Instant Client on MacOS

### ISSUE THREAD

**Issue by IdemenB** [kubo/rust-oracle#34]
Hi, after spending a few hours and being unable to configure the PATH or environment variable for Oracle Instant Client, I decided to ask for your help here as the last resort. Has anyone configured whatever is required for Oracle Instant Client on MacOs Big Sur?

This is the error I'm getting:

`DPI Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help`

I've been trying to set the following, but whatever I tried has not worked:

`Alternatively, set DYLD_LIBRARY_PATH to the Instant Client directory. Note this variable does not propagate to sub-shells.
`

**Comment by cjbj** [comment]
I don't know enough about Rust to know how, or whether, you can set https://github.com/kubo/rust-oracle/blob/v0.5.1/src/binding.rs#L1659.  If not, then find where the binary module is and in that same directory run something like `ln -s ~/Downloads/instantclient_19_8/libclntsh.dylib .`  I will defer to @kubo, who has a great understanding of all this

**Comment by kubo** [comment]
@IdemenB 
Which architecture of macOS do you use? Intel or Apple Silicon?

It works for my intel mac. I'm using a little old Big Sur
```shell
$ uname -m
x86_64
$ sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
```

If your mac is Apple Silicon, it may work by creating x86_64 programs. Well, I have tried it.

**Comment by IdemenB** [comment]
Thank you all, my setting is Mac Os Big Sur 11.3 running on Intel i7 Macbook Pro. Copying libclntsh.dylib into the main folder worked.

**Comment by yuyang-ok** [comment]
>  Copying libclntsh.dylib into the main folder worked. 


@IdemenB  I am having the same issue too?
copy `libclntsh.dylib` to where???
