### ISSUE TITLE
ROWID type documentation

### ISSUE THREAD

**Issue by daviessm** [kubo/rust-oracle#36]
I need to get the value of ROWIDs selected from a table in the format `select rowid from table1` but the `Rowid` type doesn't seem to be castable to any type in Rust - please could you document in the `FromSql` trait how I can reference it as a string (as would be returned by `ROWIDTOCHAR`)?

**Comment by kubo** [comment]
Could you use `ROWIDTOCHAR` for now?
I'll release the next version within a week. It will allow you to get a rowid as a string.

**Comment by daviessm** [comment]
Awesome, I can wait a week - thanks!

**Comment by kubo** [comment]
0.5.2 was released.

**Comment by daviessm** [comment]
Works perfectly, thanks
