### ISSUE TITLE
Request for setting statement properties ROW_PREFETCH and LOBPREFETCH_SIZE

### ISSUE THREAD

**Issue by daviessm** [kubo/rust-oracle#39]
I would like to be able to set the properties DEFAULT_LOBPREFETCH_SIZE and DEFAULT_ROW_PREFETCH when connections are created (incl. pooled connections from r2d2_oracle): https://docs.oracle.com/cd/E18283_01/appdev.112/e10646/ociaahan.htm#sthref5292

**Comment by daviessm** [comment]
LOBPREFETCH_SIZE isn't yet implemented in ODPI-C, I've requested it here: https://github.com/oracle/odpi/issues/163

**Comment by kubo** [comment]
In https://github.com/oracle/odpi/issues/163#issuecomment-865092840
> I'll add `Statement.define()` to rust-oracle.

I didn't after I thought about use cases. Instead, I changed [the type for LOB columns to string](https://github.com/kubo/rust-oracle/commit/d29652c1bcb02403d97a627a0503c67b7a8a4720#diff-fdbffa5e7a50bcc767fff75f5c23b30abacf30cebee409d37a9e8669510135ccR889-R896) to follow @anthony-tuininga's suggestion.

**Comment by anthony-tuininga** [comment]
Returning CLOBs as strings and BLOBs as bytes (whatever those are called in Rust!) makes good sense. There may still be occasions, however, where you want to return the LOB -- for those cases where you have a LOB that won't fit in memory and you want to only read or write portions of it at a time. There are rare, but definitely exist!

**Comment by kubo** [comment]
@anthony-tuininga I agree with you.

I have a plan to support reading and writing portions of LOBs. I did it two month ago in my local repository excluding documentation and small tweaks. When I make it public, I'll add a statement parameter to get LOB column data as Lob data types. I thought that they were rare so LOB data are got as strings or bytes by default.

**Comment by daviessm** [comment]
Resolved with https://github.com/kubo/rust-oracle/commit/7ec5577c7b83ac761f9cbc6cc97a3aaac858b8df - configurability of ROW_PREFETCH; and https://github.com/kubo/rust-oracle/commit/d29652c1bcb02403d97a627a0503c67b7a8a4720 - directly access CLOBs as Strings and BLOBs as bytes

**Comment by kubo** [comment]
FYI though the following may be unnecessary by https://github.com/kubo/rust-oracle/commit/d29652c1bcb02403d97a627a0503c67b7a8a4720.

I added [`Connection::set_oci_attr`](https://github.com/kubo/rust-oracle/blob/7fb2379cbb0cd1e80b657e4c47abb7cd10ded8e0/src/connection.rs#L1515-L1517) corresponding to [`dpiConn_setOciAttr`](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_setOciAttr), which sets OCI handle attributes to connections.
I also added types corresponding to some OCI handle attributes, including `DEFAULT_LOBPREFETCH_SIZE`. See [here](https://github.com/kubo/rust-oracle/blob/7fb2379cbb0cd1e80b657e4c47abb7cd10ded8e0/src/oci_attr/mod.rs#L162-L194).

Note: `Connection::set_oci_attr` may be changed to `unsafe` function later.
