### ISSUE TITLE
Is it possible to support failover option?

### ISSUE THREAD

**Issue by madmaxio** [kubo/rust-oracle#4]
Is it possible to support failover - with multiple server endpoints in a connection string?

**Comment by kubo** [comment]
It seems to be supported by Oracle itself.
See https://docs.oracle.com/database/121/NETRF/tnsnames.htm#NETRF272

If you uses ORACLE_HOME-based client, add a net service name including multiple address lists into `$ORACLE_HOME/network/admin/tnsnames.ora` and use the name to connect to servers.
```rust
let conn = Connection::connect(username, password, net_service_name, &[])?;
```

If you uses Oracle instant client, create a file `tnsnames.ora` including the net service name and set the environment variable `TNS_ADMIN` pointing to the directory containing the the file.

If you need to set server endpoints at runtime, make a connect descriptor and use it.
```rust
let host1 = "host1";
let port1 = 1521;
let service_name1 = "service_name1";
let host2 = "host2";
let port2 = 1521;
let service_name2 = "service_name2";
let connect_desc = format!(r#"(DESCRIPTION_LIST=
  (FAILOVER=on)
  (DESCRIPTION=
    (ADDRESS=(PROTOCOL=tcp)(HOST={})(PORT={}))
    (CONNECT_DATA=(SERVICE_NAME={})))
  (DESCRIPTION=
    (ADDRESS=(PROTOCOL=tcp)(HOST={})(PORT={}))
    (CONNECT_DATA=(SERVICE_NAME={}))))"#,
    host1, port1, service_name1, host2, port2, service_name2);
let conn = Connection::connect(username, password, &connect_desc, &[])?;
```
Well, I have not tried it. I hope it works.

See [here](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/netag/enabling-advanced-features.html#GUID-8F532535-C401-4B51-BE0B-04FD74BB0621) if you needs not only connect-time failover but also transparent application failover.

**Comment by madmaxio** [comment]
Runtime connect descriptor worked perfectly, thx a lot.
