### ISSUE TITLE
Prefetch example tweak

### ISSUE THREAD

**Issue by cjbj** [kubo/rust-oracle#42]
@kubo apologies if you already have this queued up from the email I sent about it.

I think the comment in [connection.js](https://github.com/kubo/rust-oracle/blob/master/src/connection.rs#L692-L693) about prefetch size could should show a value one greater than the number of rows.  I.e this:

```
    /// let mut stmt = conn
    ///     .statement("select empno, ename from emp order by empno fetch first 10 rows only")
    ///     .prefetch_rows(10)
    ///     .build()?;
```
could be:
```
    /// let mut stmt = conn
    ///     .statement("select empno, ename from emp order by empno fetch first 10 rows only")
    ///     .prefetch_rows(11)  /// add one to avoid a round-trip to check for end-of-fetch
    ///     .build()?;
```
It depends what cases you want to show.

**Comment by kubo** [comment]
@cjbj Thanks for pointing and sorry for too late reply. I received your email.

**Comment by cjbj** [comment]
@kubo thank you for all your great work.
