### ISSUE TITLE
`Connection::object_type` cache prevents connection drop

### ISSUE THREAD

**Issue by Flowneee** [kubo/rust-oracle#48]
# Problem

Object type cache in connection prevents connection drop, since `ObjectTypeInternal` inside `InnerConn` have an `Conn (Arc<InnerConn>)` to this connection, creating cycle.

# Example

Example below will always create new connections without dropping previous, leading to memory and socket leaks. This can be checked with `$ sudo netstat -tnp | grep <app_name> | grep <port> | grep ESTAB | wc -l`. Uncommenting `//conn.close().unwrap(); ` won't help - socket will be closed, but memory will still leak. Also this can be checked with `$ DPI_DEBUG_LEVEL=95 cargo run` - ODPI logs will show that old connection is not released.

```rust
fn main() {
    let connector = oracle::Connector::new("user", "password", "conn_str");
    loop {
        let conn = connector.connect().unwrap();
        drop(conn.object_type("some_type").unwrap());
        //conn.close().unwrap(); 
        std::thread::sleep(std::time::Duration::from_secs(3));
    }
}
```

# Possible solution

I have not found one yet, since there is many Arc's in library, which references same connection from different places, so I doubt this can be easily fixed without many changes. At least it is good idea to document this behavior.

**Comment by kubo** [comment]
Thanks for pointing! I'll check it.

**Comment by kubo** [comment]
I must use [weak reference](https://doc.rust-lang.org/book/ch15-06-reference-cycles.html#preventing-reference-cycles-turning-an-rct-into-a-weakt) somewhere.

**Comment by kubo** [comment]
@Flowneee 
Could you try e73d167?
```toml
[dependencies]
oracle = { git = "https://github.com/kubo/rust-oracle", rev = "e73d167" }
```

As far as I checked, your code works fine without socket leaks. I have not checked memory leaks yet but I guess that it is also fixed.
I'll think about references more. The number of reference count is bigger than I had thought.

**Comment by Flowneee** [comment]
Yes, I don't see any sockets or memory leaks. And since `Connection` is not stored anywhere inside library types, I think this fix is OK.

**Comment by kubo** [comment]
0.5.4 was released.
