### ISSUE TITLE
Procedural macro for `RowValue`

### ISSUE THREAD

**Issue by Flowneee** [kubo/rust-oracle#49]
Implementations of `RowValue` for structs is usually simple and all similar, so it make sense to make `#[derive(RowValue)]` macro (in our case we had struct with over 150 fields). We currently have our own implementation of this procedural macro and we want to have it in `rust-oracle`. Do you interested in PR in this repo (with proc-macro crate, enabled by feature) or should we publish it separately?

## Example

```rust
#[derive(RowValue)]
struct Row {
    id: i64,
    #[row_value(rename = "timestamp")
    ts: NaiveDateTime,
    #[row_value(with = "custom::parse::fn")]
    name: Option<String>,
}
```

**Comment by kubo** [comment]
@Flowneee 
Thanks. It is very interesting. The pull request is welcome!

**Comment by kubo** [comment]
Thanks! https://github.com/kubo/rust-oracle/pull/51 was merged.

I'll revise doc comment about the `RowValue` derive macro later because it is placed in [docs about the oracle crate](https://www.jiubao.org/rust-oracle/oracle/index.html#derives).
