### ISSUE TITLE
Request cancellation

### ISSUE THREAD

**Issue by Niedzwiedzw** [kubo/rust-oracle#56]
Hey, sometimes requests to my db take quite a long time, I'd like to be able to drop the connection and cancel all the requests that are going on somehow - could I do this? great job on this crate btw, it works like a charm, cheers

**Comment by Niedzwiedzw** [comment]
> Hey, sometimes requests to my db take quite a long time, I'd like to be able to drop the connection and cancel all the requests that are going on somehow - could I do this? cheers

**Comment by kubo** [comment]
How about [`Connection::set_call_timeout`] or [`Connection::break_execution`]?

[`Connection::set_call_timeout`]: https://www.jiubao.org/rust-oracle/oracle/struct.Connection.html#method.set_call_timeout
[`Connection::break_execution`]: https://www.jiubao.org/rust-oracle/oracle/struct.Connection.html#method.break_execution
