### ISSUE TITLE
use semantic versioning & follow changelog standards

### ISSUE THREAD

**Issue by rursprung** [kubo/rust-oracle#57]
i'd strongly suggest to move to using [Semantic Versioning](https://semver.org/spec/v2.0.0.html) for this repository to make it easier for consumers to use it.

e.g. somewhere between 0.5.1 and 0.5.5 (presumably with 0.5.5 itself) support for rustc 1.42.0 has been removed (the minimum version required now is 1.54.0), so this should've been a 0.6.0 release instead.

using semantic versioning will clearly tell consumers what to expect when they update to a new version. also, the whole dependency version management system of cargo is built around semantic versioning (see [the docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field)).

on a related note i'd suggest to move your changelog to follow [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) to keep things more standardised (your changelog is already pretty closely aligned with this and will only need some minor enhancements for it to follow the standard).

**Comment by kubo** [comment]
Thanks. It is good opportunity for me to think about minimum supported ruby version again.

> e.g. somewhere between 0.5.1 and 0.5.5 (presumably with 0.5.5 itself) support for rustc 1.42.0 has been removed (the minimum version required now is 1.54.0), so this should've been a 0.6.0 release instead.

I don't think that it is a breaking change. It depends on the policy of the maintainers  (e.g. [tokio](https://github.com/tokio-rs/tokio#supported-rust-versions), [async-std](https://book.async.rs/overview/stability-guarantees.html#minimum-version-policy)) according to the cargo book.

In the cargo book, [changing the minimum version of Rust required is categorized as "Possibly-breaking"](https://doc.rust-lang.org/cargo/reference/semver.html#possibly-breaking-changing-the-minimum-version-of-rust-required).

Possibly-breaking is:
> The "Possibly-breaking" category covers changes that have the potential to break during an update, but may not necessarily cause a breakage. The impact of these changes should be considered carefully. The exact nature will depend on the change and the principles of the project maintainers.

I avoid to use too recent rust versions. For example, I wrote code only working on rust 1.60.0+ ([`dep:` prefix in the `[features]` table](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features)) in my local rust-oracle 0.6.0-dev branch just before and then I rewrote it to work on older ones. (Rust 1.61.0 is the latest stable version at present.) However I have not defined the policy. Your suggestions is good opportunity to define it.

> on a related note i'd suggest to move your changelog to follow [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) to keep things more standardised (your changelog is already pretty closely aligned with this and will only need some minor enhancements for it to follow the standard).

It is worth to adopt it partly. However I don't think that it is the standard at present. In the [FAQ](https://keepachangelog.com/en/1.0.0/#frequently-asked-questions), "Is there a standard changelog format?" "Not really."

**Comment by kubo** [comment]
I added "[Supported Rust Versions](https://github.com/kubo/rust-oracle/tree/v0.5.6#supported-rust-versions)" to `README.md`.
