### ISSUE TITLE
Any reason SqlValues are .dup_by_handle()'d on retrieving a row?

### ISSUE THREAD

**Issue by christoph-heiss** [kubo/rust-oracle#60]
Hi,

as the title says.
During profiling of retrieving large sets of data from Oracle databases, I noticed that `<Row as RowValue>::get()` prominently stands out if there are lots of small rows.

For each row, the value handles are duplicated - is there any specific reason for this? If there is, than the following is probably wrong and I'd have to accept the sizeable performance hit.
I created a [small patch](https://github.com/christoph-heiss/rust-oracle/commit/6a01b5d4ec61ff66c1333110f6ffc45481c1ba91) which shares the values across row, which worked fine so far. 

Thanks,
Christoph

**Comment by kubo** [comment]
> For each row, the value handles are duplicated - is there any specific reason for this? If there is, than the following is probably wrong and I'd have to accept the sizeable performance hit.

That's because if handle isn't duplicated, fetching a next row changes the previously fetched rows.

For example:
```rust
use oracle::Connection;

fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    let conn = Connection::connect("odpic", "welcome", "")?;
    let mut stmt = conn
        .statement("select level from dual connect by level <= 4")
        .build()?;
    let mut result_set = stmt.query(&[])?;
    println!("fetch first row");
    let first_row = result_set.next().unwrap()?;
    println!("  content of first row: {}", first_row.get::<usize, i32>(0)?);

    println!("fetch second row");
    let second_row = result_set.next().unwrap()?;
    println!("  content of first row: {}", first_row.get::<usize, i32>(0)?);
    println!("  content of second row: {}", second_row.get::<usize, i32>(0)?);

    Ok(())
}
```
The above prints:
```
fetch first row
  content of first row: 1
fetch second row
  content of first row: 1
  content of second row: 2
```
When your patch is applied, the first row is changed by the second fetch as follows:
```
fetch first row
  content of first row: 1
fetch second row
  content of first row: 2
  content of second row: 2
```
