### ISSUE TITLE
Any idea why I'm getting `DPI Error: DPI-1080: connection was closed by ORA-3156`

### ISSUE THREAD

**Issue by Niedzwiedzw** [kubo/rust-oracle#65]
This happens randomly, I'm not getting it when executing the same queries using say DataGrip

**Comment by kubo** [comment]
What version of Oracle database client do you use?
What version of Oracle database server do you use?
What version of rust-oracle do you use?

ORA-3156 is related to [`OCI_ATTR_CALLTIMEOUT`](https://docs.oracle.com/en/database/oracle/oracle-database/21/lnoci/handle-and-descriptor-attributes.html#GUID-D8EE68EB-7E38-4068-B06E-DF5686379E5E__GUID-C63B3ABA-DD99-4342-8B78-0E994A4CF739). Did you execute time-consuming queries?

How about call_timeout?
* [`Connection.call_timeout`](https://docs.rs/oracle/0.5.6/oracle/struct.Connection.html#method.call_timeout)
* [`Connection.set_call_timeout`](https://docs.rs/oracle/0.5.6/oracle/struct.Connection.html#method.set_call_timeout)

**Comment by cjbj** [comment]
Also are there any sqlnet.ora files with timeout parameters set?

**Comment by Niedzwiedzw** [comment]
Thank you for responding, I have simplified my code a bit (removed the r2d2 pool altogether). My use case is that the databases I'm connecting to are on some rural locations, with very bad internet connectivity. Oracle version is also pretty old (~11b I believe). Anyways, this problem no longer occurs, thank you for your answers
