### ISSUE TITLE
Usage with asynchronous code problem - how to shut down `.connect()` call that hangs indefinitely

### ISSUE THREAD

**Issue by Niedzwiedzw** [kubo/rust-oracle#66]
My problem now is that some of the connections just hang indefinitely.
my code: 
```rust
#[instrument(skip_all)]
async fn acquire_connection(
    OracleConnectionCredentials {
        username,
        password,
        connect_string,
    }: OracleConnectionCredentials,
) -> Result<Arc<Connection>> {
    tokio::task::spawn_blocking(move || {
        debug!("getting connection out of a pool");
        let conn = oracle::Connector::new(username, password, connect_string)
            .purity(oracle::conn::Purity::New)
            .connect()
            .map(Arc::new);
        conn
    })
    .await
    .wrap_err("thread crashed")
    .and_then(|v| v.wrap_err("acquiring"))
}
```
can I either give it some timeout or break this process externally?

**Comment by Niedzwiedzw** [comment]
more context: 
`.connect()` hangs with 1 (!) database out ot 113 databases  I'm connecting to. 
internet connection is surprisingly OK  for this one (5MB/s upload and download). 
restarting my backend fixes it for 1 connection, but any subsequent connections fail.

**Comment by kubo** [comment]
How about setting [`SQLNET.OUTBOUND_CONNECT_TIMEOUT`](https://docs.oracle.com/en/database/oracle/oracle-database/21/netrf/parameters-for-the-sqlnet.ora.html#GUID-0857C817-675F-4CF0-BFBB-C3667F119176) in [sqlnet.ora](https://docs.oracle.com/en/database/oracle/oracle-database/21/netrf/parameters-for-the-sqlnet.ora.html#GUID-19423B71-3F6C-430F-84CC-18145CC2A818)?

**Comment by Niedzwiedzw** [comment]
sadly I have no control over that database's configuration...

**Comment by Niedzwiedzw** [comment]
would it be hard to add a timeout to `.connect()` in `oracle-rust` ?

**Comment by cjbj** [comment]
> sadly I have no control over that database's configuration...

You would set [SQLNET.OUTBOUND_CONNECT_TIMEOUT](https://docs.oracle.com/en/database/oracle/oracle-database/21/netrf/parameters-for-the-sqlnet.ora.html#GUID-0857C817-675F-4CF0-BFBB-C3667F119176) in [sqlnet.ora](https://docs.oracle.com/en/database/oracle/oracle-database/21/netrf/parameters-for-the-sqlnet.ora.html#GUID-19423B71-3F6C-430F-84CC-18145CC2A818) on the machine where you run Rust, not on the database tier.  The potential locations for the file can be gleaned from [this doc](https://oracle.github.io/node-oracledb/doc/api.html#tnsadmin).

**Comment by Niedzwiedzw** [comment]
OH!!!! yes it worked ,thank you so much @cjbj
