### ISSUE TITLE
How to change the value of "oracleClientLibDir" in dpiContextCreateParams struct

### ISSUE THREAD

**Issue by daidaiSeniorBrother** [kubo/rust-oracle#68]
Hello,
I want to customize the directory of Oracle Instant Client，How to operate？
Thanks

**Comment by kubo** [comment]
It isn't available now. It will be supported at the next release.
I've done it about 5 months ago in a local branch but haven't merged it yet.

**Comment by daidaiSeniorBrother** [comment]
> It isn't available now. It will be supported at the next release. I've done it about 5 months ago in a local branch but haven't merged it yet.

Thanks for your reply. For the time being, I solved my problem by changing the source code. During initialization, I passed in my own dpiContextCreateParams structure
