### ISSUE TITLE
API to upload file as BLOB without preallocation

### ISSUE THREAD

**Issue by mcpiroman** [kubo/rust-oracle#70]
Hi, 
is there any API to load file (or other stream data) without loading it entirely to memory?

Right now I do:
```rust
let mut file = File::open(&schema_file.path)?;
let mut blob = Blob::new(&conn)?;
io::copy(&mut file, &mut blob)?;
stmt.execute(&[&blob])?;
```

for comparison, jdbc has
```java
void setBlob(int parameterIndex, InputStream inputStream)
```

**Comment by kubo** [comment]
> is there any API to load file (or other stream data) without loading it entirely to memory?

Yes.
Your example sends file contents to the server for each [`Blob::write`](https://docs.rs/oracle/0.5.6/oracle/sql_type/struct.Blob.html#method.write) inside of `io::copy`.

`Blob::write` internally calls [`dpiLob_writeBytes`](https://oracle.github.io/odpi/doc/functions/dpiLob.html#c.dpiLob_writeBytes), which requires network round-trips as listed [here](https://oracle.github.io/odpi/doc/user_guide/round_trips.html). If `Blob::write` stores bytes to memory, no round-trips are required.

**Comment by mcpiroman** [comment]
OK, so that's why `Blob::new` requires &connection.
I did not think that was the case as I not expect anything to be sent before `execute`.

Anyway, big thanks.

**Comment by kubo** [comment]
[`io::copy`] uses 8K buffer for [non-specialized implementation]. I think that it is too small for network I/O. It is better to use [`BufWriter::with_capacity()`] to increase the size.

[`io::copy`]: https://doc.rust-lang.org/std/io/fn.copy.html
[non-specialized implementation]: https://github.com/rust-lang/rust/blob/1.66.0/library/std/src/io/copy.rs#L137-L163
[`BufWriter::with_capacity()`]: https://doc.rust-lang.org/std/io/struct.BufWriter.html#method.with_capacity

```rust
let buffer_size = 256 * 1024; // This is by guesswork. The proper size depends on the network environment.
let mut file = File::open(&schema_file.path)?;
let mut blob = BufWriter::with_capacity(buffer_size, Blob::new(&conn)?);
io::copy(&mut file, &mut blob)?;
blob.flush()?; // Don't forget this.
stmt.execute(&[blob.get_ref()])?;
```
