### ISSUE TITLE
the `?` operator can only be used in a function that returns `Result` or `Option`

### ISSUE THREAD

**Issue by ryvdx** [kubo/rust-oracle#72]
Any help with this? Using your example, but getting a compile time errors. (copy/pasted your code)

"let row = row_result?;"
Produces a compile time error of:

the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `FromResidual`)
the trait `FromResidual<Result<Infallible, oracle::Error>>` is not implemented for `()`

Get that on each of the lines below on the ? character.

```
    // Run Oracle Query
    let rows = conn.query("SELECT myname, myvalue FROM marktest", &[&30])?;
    for row_result in rows {
        let row = row_result?;
        let myname: String = row.get(0)?;
        let myvalue: String = row.get(1)?;
        println!(" {:14}| {:>10}    ", myname, myvalue);
    }
```

**Comment by kubo** [comment]
You need to learn [error handling](https://doc.rust-lang.org/book/ch09-00-error-handling.html). Especially [this section](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#the--operator-can-be-used-in-functions-that-return-result).

Examples use `?` to follow [this API guideline](https://rust-lang.github.io/api-guidelines/documentation.html#c-question-mark).
