### ISSUE TITLE
Question - Alter Sessions

### ISSUE THREAD

**Issue by sentrisable** [kubo/rust-oracle#76]
Reading through the docs, you can set the NLS_LANG parameters using the std::env::set_var. My question is if it possible to set other session parameters using the std::env::set_var (eg NLS_DATE) or is it limited just to the NLS_LANG and the other parameters need to be set through Connection::execute.

**Comment by kubo** [comment]
See Scope (E = Environment Variable, A = ALTER SESSION)  in https://docs.oracle.com/en/database/oracle/oracle-database/21/nlspg/setting-up-globalization-support-environment.html#GUID-6475CA50-6476-4559-AD87-35D431276B20__G1012703.
