### ISSUE TITLE
A way to set path for oracle instant client

### ISSUE THREAD

**Issue by sakshatshinde** [kubo/rust-oracle#77]
Similar to how `cx_Oracle` allows users to set the lib path for instant client, is there a way to do this in `rust-oracle` without using `LD_LIBRARY_PATH`?
```py
cx_Oracle.init_oracle_client(lib_dir= r"c:\path_to_libraries")
```

The Error I am getting is following,
`Error: DPI Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "Dynamic loading not supported". See https://oracle.github.io/odpi/doc/installation.html#linux for help`

My `$ORACLE_HOME` is `/oravl01/oracle/12.1.0.2` and this is something that I've not set, it was already there, maybe some other applications are using this.

I do not want to break things, so I was wondering if there is a way specifically set a path for the instant oracle client.

PS: This is an old enterprise centos7 machine where I can't risk changing things I don't know about.

**Comment by sakshatshinde** [comment]
Also am I getting `Dynamic loading not supported` because my target is `musl`?

**Comment by kubo** [comment]
> Similar to how cx_Oracle allows users to set the lib path for instant client, is there a way to do this in rust-oracle without using LD_LIBRARY_PATH?

Not yet. I implemented it at least three times in my local machine but have not merged it yet.

> Also am I getting `Dynamic loading not supported` because my target is musl?

I don't recommend to use musl. I believe that Oracle client libraries isn't available with it though I've not tested it.
