### ISSUE TITLE
How to extract `Geometry` type.

### ISSUE THREAD

**Issue by yuyang-ok** [kubo/rust-oracle#79]
I am new to this lib,is there am example to extract geometry type.
geometry often represent as `WKB` , `EWKB` etc ...

**Comment by kubo** [comment]
You can use [`SDO_UTIL.TO_WKBGEOMETRY`] to convert sdo_geometry type to WKB.

```rust
let sql = "select id, SDO_UTIL.TO_WKBGEOMETRY(geometry_column) from geometry_table";
for row_result in conn.query_as::<(i64, Vec<u8>)>(sql, &[])? { // fetch the second column as Vec<u8>.
    let row = row_result?;
    println!("{}, {:?}", row.0, row.1);
}
```

[`get_wkb`] method is available in a PL/SQL block.

[`SDO_UTIL.TO_WKBGEOMETRY`]: https://docs.oracle.com/en/database/oracle/oracle-database/19/spatl/SDO_UTIL-reference.html#GUID-6C713D70-85B1-44B3-897C-6EA6B8E76C17
[`get_wkb`]: https://docs.oracle.com/en/database/oracle/oracle-database/19/spatl/spatial-datatypes-metadata.html#GUID-9BE85C1A-B96B-4CDB-A202-11AFFC7E9FC1__CBBCCIIA

**Comment by yuyang-ok** [comment]
thanks.
