### ISSUE TITLE
Ability to auto-gen structs from db

### ISSUE THREAD

**Issue by sakshatshinde** [kubo/rust-oracle#84]
SeaORM has a cli to generate all the structs from a db to a file.

[See here](https://www.sea-ql.org/SeaORM/docs/generate-entity/sea-orm-cli/)

What do you think about this feature?

**Comment by kubo** [comment]
I would appreciate if anyone releases a crate having the feature.
ORM is out of scope for this project.

**Comment by sakshatshinde** [comment]
Not a crate but tried something very crude. [ora-reflector](https://github.com/sakshatshinde/ora-reflector)
