### ISSUE TITLE
how can I get decimal value? like Number(28,18)

### ISSUE THREAD

**Issue by tc19901016** [kubo/rust-oracle#90]
In jdbc, java has [resultSet.getDecimal()] method to get big number. But I'm not sure if Rust has the similar method.
If I use row.get::<_, f64>, the column value will loss precision.

thank you.

**Comment by kubo** [comment]
Gets the column value as String and converts it to any decimal type.
If rust had a decimal type natively, I would implement `FromSql` for the type.
