### ISSUE TITLE
DESCRIBE Statement

### ISSUE THREAD

**Issue by Lurgrid** [kubo/rust-oracle#91]
Hello, 

I would like to open this issue, because the statement ``DESCRIBE`` is considered as ``Unknown``, while it is a valid request on the oracle database here is the doc

https://docs.oracle.com/javadb/10.8.3.0/tools/rtoolsijcomrefdescribe.html

**Comment by kubo** [comment]
> while it is a valid request on the oracle database here is the doc

That's because `DESCRIBE` is a command supported by the tool. It isn't a valid SQL statement.

Use `select * from all_tab_columns where owner = ... and table_name = ...` instead.

**Comment by Lurgrid** [comment]
Ah okay, I was thinking, sorry for opening an issue for nothing
