### ISSUE TITLE
Question - How to execute a "where in" query?

### ISSUE THREAD

**Issue by muturgan** [kubo/rust-oracle#93]
I have found a simple example from a crate documentation:
```
let sql = "select ename, sal, comm from emp where deptno = :1";
let rows = conn.query(sql, &[&30])?;
```
But I have a list of values: `client_ids: Vec<String>`.
Can I bind a vec/slice value and execute a `where in / any` query?

**Comment by kubo** [comment]
See https://github.com/kubo/rust-oracle/issues/25
